---
title: "Hello from the Team"
authors: 
- Franziska Pradel
- Franziska Deeg
- Lea Kaftan

date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Mission Statement: 

Wir sind vier Forscherinnen am Cologne Center for Comparative Politics (CCCP) an der Universität zu Köln, die ihre Doktorarbeiten in verschiedenen Themengebieten der Politikwissenschaft schreiben.
<!--more-->


Unser Arbeitsalltag besteht hauptsächlich aus der Bearbeitung und Analyse von Daten, durch die wir wichtige Einblicke in Politik, Wirtschaft und die Gesellschaft erhalten. Dieses Wissen wollen wir gerne mit euch teilen und euch in unserem einwöchigen Datascience Workshop “Hack your Future” an die Arbeit mit Daten heranführen. In Zeiten der fortschreitenden Digitalisierung sind Daten überall zu finden und können für uns sehr nützlich und spannend sein. Das haben auch Universitäten und Unternehmen erkannt, was Datascience in vielen Bereichen immer wichtiger macht. In dem Kurs lernt ihr, wo ihr Daten findet, sie euch für Analyse und Visualisierungen zu Nutze macht und wir ihr sie auf einer Onlineplattform präsentieren könnt. Dafür werden wir euch die Grundsätze der Software R beibringen, mit der ihr all das einfach und schnell umsetzen könnt. Jeder kann lernen mit Daten kreativ zu werden! 



Here we have a small presentation of organizers, their professional background as well as research interests.

